version: '3.5'

volumes:
  postgres_data:
    driver: local
    driver_opts:
            device: /home/cagla/data/database
            o: bind
            type: none


services:
  db:
    image: postgres
    restart: always
    container_name: postgres_db
    env_file:
      - ./project/app/.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data]
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "cagla", "-d", "dbtest"]
      interval: 5s
      timeout: 20s
      retries: 2
    

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./project/app/.env
    ports:
      - '8000:8000'
    restart: 'on-failure:10'
