version: '3.6'

volumes:
  postgres_data:
    driver: local
    driver_opts:
            device: /var/docker_volumes/database
            o: bind
            type: none


services:
  db:
    build: ./database/
    hostname: postgres_db
    restart: always
    container_name: postgres_db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/docker_volumes/database
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 3s
      timeout: 10s
      retries: 2
    
    networks:
      - newone
    

  web:
    hostname: backend
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8100:8000
    restart: 'on-failure:1'

    networks:
      - newone


networks:
  newone:
    driver: bridge
