services:

  web:
    build: .
    ports:
      - "80:8000"
    depends_on:
      db:
        condition: service_healthy
    command: ["python3", "./project/manage.py", "runserver"]

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dbtest
    volumes:
      - ./dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
    restart: always

