version: '3.5'

networks:
    localhost:
        name: inet

volumes:
  postgres_data:
    driver: local
    driver_opts:
            device: /home/cagla/data/database
            o: bind
            type: none


services:
  db:
    image: postgres
    restart: always
    networks:
      - localhost
    env_file:
      - ./project/app/.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  web:
    build: .
    networks:
      - localhost
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./project/app/.env
    command: ["python3", "./project/manage.py", "runserver", "0.0.0.0:8000"]
