# Generated by Django 4.2.7 on 2023-12-18 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('player1_id', models.IntegerField(default=0)),
                ('player2_id', models.IntegerField(default=0)),
                ('player1_score', models.IntegerField(default=0)),
                ('player2_score', models.IntegerField(default=0)),
                ('winner_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('players', models.JSONField(default=list)),
                ('winner1_id', models.IntegerField(default=0)),
                ('winner2_id', models.IntegerField(default=0)),
                ('waitlist', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('avatar', models.ImageField(default='avatars/default.jpg', upload_to='avatars/')),
                ('total_played', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('friends', models.JSONField(default=list)),
                ('lan', models.CharField(default='tr', max_length=2)),
                ('nickname', models.CharField(default='nickname', max_length=30, primary_key=True, serialize=False)),
                ('is_online', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
