# Generated by Django 4.2.7 on 2023-11-16 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_rename_user_dbuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DBUser',
            new_name='User',
        ),
    ]
