# Generated by Django 4.2.7 on 2023-11-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_normaluser_user_delete_auth42user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=100),
        ),
    ]
