# Generated by Django 4.2.7 on 2023-11-16 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_user_token'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='DBUser',
        ),
    ]
