# Generated by Django 4.2.7 on 2023-11-09 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_normaluser_rename_user_auth42user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='normaluser',
            old_name='username',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='normaluser',
            old_name='password',
            new_name='token',
        ),
    ]
