# Generated by Django 4.2.7 on 2023-11-09 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_username_normaluser_login_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NormalUser',
            new_name='User',
        ),
        migrations.DeleteModel(
            name='Auth42User',
        ),
    ]
